project:
    type: website
    
website: 
  title: "Notes on Discrete Response"
  navbar: 
    left: 
      - wk1.qmd
      - wk2.qmd
      - wk3.qmd
      - wk4P1.qmd
      - wk4P2.qmd
      - wk4P3.qmd
      - wk5.qmd
      