project:
    type: website
    
website: 
  title: "Discrete Response"
  navbar: 
    left: 
      - wk1.qmd
      - wk2.qmd
      - wk4P1.qmd
      - wk4P2.qmd
      - wk4P3.qmd
      - wk5.qmd
      