<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Logistic regression – Notes on Discrete Response</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-b53751a350365c71b6c909e95f209ed1.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-ddd961a2510921635943dfbbd19534c4.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-dc9e717b3fbf52f64798667d9ecbfc31.min.css" rel="prefetch" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>

<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">


  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="style.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Notes on Discrete Response</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./wk1.html"> 
<span class="menu-text">One and Two binary groups</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./wk2.html" aria-current="page"> 
<span class="menu-text">Logistic regression</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./wk3.html"> 
<span class="menu-text">Logistic regression Part 2</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./wk4P1.html"> 
<span class="menu-text">Multinomial Probability</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./wk4P2.html"> 
<span class="menu-text">Nominal Response</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./wk4P3.html"> 
<span class="menu-text">Ordinal response regression models</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./wk5.html"> 
<span class="menu-text">Logistic regression</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#logistic-regression" id="toc-logistic-regression" class="nav-link active" data-scroll-target="#logistic-regression">Logistic regression</a>
  <ul class="collapse">
  <li><a href="#functional-form" id="toc-functional-form" class="nav-link" data-scroll-target="#functional-form">Functional form</a></li>
  <li><a href="#parameter-estimation-in-r" id="toc-parameter-estimation-in-r" class="nav-link" data-scroll-target="#parameter-estimation-in-r">parameter estimation in R</a></li>
  </ul></li>
  <li><a href="#odds" id="toc-odds" class="nav-link" data-scroll-target="#odds">ODDS</a></li>
  <li><a href="#log-odds-to-probability" id="toc-log-odds-to-probability" class="nav-link" data-scroll-target="#log-odds-to-probability">Log odds to probability</a></li>
  <li><a href="#case-study-south-african-heart-disease" id="toc-case-study-south-african-heart-disease" class="nav-link" data-scroll-target="#case-study-south-african-heart-disease">Case Study: South African Heart Disease</a>
  <ul class="collapse">
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#data-description" id="toc-data-description" class="nav-link" data-scroll-target="#data-description">Data Description</a></li>
  </ul></li>
  <li><a href="#exploratory-analysis" id="toc-exploratory-analysis" class="nav-link" data-scroll-target="#exploratory-analysis">Exploratory Analysis</a>
  <ul class="collapse">
  <li><a href="#univariate-analysis" id="toc-univariate-analysis" class="nav-link" data-scroll-target="#univariate-analysis">Univariate Analysis</a></li>
  <li><a href="#bivariate-analysis" id="toc-bivariate-analysis" class="nav-link" data-scroll-target="#bivariate-analysis">Bivariate Analysis</a></li>
  </ul></li>
  <li><a href="#model-development" id="toc-model-development" class="nav-link" data-scroll-target="#model-development">Model Development</a>
  <ul class="collapse">
  <li><a href="#linear-probability-model" id="toc-linear-probability-model" class="nav-link" data-scroll-target="#linear-probability-model">Linear probability model</a></li>
  <li><a href="#generalized-linear-model" id="toc-generalized-linear-model" class="nav-link" data-scroll-target="#generalized-linear-model">Generalized linear model</a>
  <ul class="collapse">
  <li><a href="#interpretation-of-model-results" id="toc-interpretation-of-model-results" class="nav-link" data-scroll-target="#interpretation-of-model-results">Interpretation of model results</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#statistical-inference" id="toc-statistical-inference" class="nav-link" data-scroll-target="#statistical-inference">Statistical Inference</a>
  <ul class="collapse">
  <li><a href="#hypothesis-test" id="toc-hypothesis-test" class="nav-link" data-scroll-target="#hypothesis-test">Hypothesis Test</a></li>
  <li><a href="#deviance" id="toc-deviance" class="nav-link" data-scroll-target="#deviance">Deviance</a></li>
  <li><a href="#confidence-interval" id="toc-confidence-interval" class="nav-link" data-scroll-target="#confidence-interval">Confidence Interval</a>
  <ul class="collapse">
  <li><a href="#confidence-interval-for-odds-ratio" id="toc-confidence-interval-for-odds-ratio" class="nav-link" data-scroll-target="#confidence-interval-for-odds-ratio">Confidence Interval for odds ratio</a></li>
  <li><a href="#confidence-interval-for-the-probability-of-success" id="toc-confidence-interval-for-the-probability-of-success" class="nav-link" data-scroll-target="#confidence-interval-for-the-probability-of-success">Confidence Interval for the Probability of Success</a></li>
  <li><a href="#final-visualization" id="toc-final-visualization" class="nav-link" data-scroll-target="#final-visualization">Final Visualization</a></li>
  <li><a href="#final-report" id="toc-final-report" class="nav-link" data-scroll-target="#final-report">Final Report</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#terms" id="toc-terms" class="nav-link" data-scroll-target="#terms">Terms</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Logistic regression</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<style>
.table-hover > tbody > tr:hover { 
  background-color: #f4f442;
}
</style>
<p>Reading CH 2.1, 2.2.1-2.2.4 (page 61- 94)</p>
<section id="logistic-regression" class="level1">
<h1>Logistic regression</h1>
<ul>
<li>In CH1, we first focused on estimating <span class="math inline">\pi</span></li>
<li>Then, <span class="math inline">\pi_1</span> and <span class="math inline">\pi_2</span> and independent groups
<ul>
<li>Briefly talked about <code>matched pair</code> case where <span class="math inline">\pi_1</span> and <span class="math inline">\pi_2</span> are dependent.</li>
</ul></li>
<li>Now we start talking about many different possible probabilities of success to estimate and perform inference upon.</li>
</ul>
<section id="functional-form" class="level2">
<h2 class="anchored" data-anchor-id="functional-form">Functional form</h2>
<p><span class="math display">\pi_i = \frac{\text{exp}(\beta_0 + \beta_1x_{i,1}+...++ \beta_px_{i,p})}{1+\text{exp}(\beta_0 + \beta_1x_{i,1}+...++ \beta_px_{i,p})}</span></p>
<p><span class="math display">\text{logit}(\pi_i)=\text{log}(\frac{\pi_i}{1-\pi_i}) = \beta_0 + \beta_1x_{i,1}+...++ \beta_px_{i,p}</span> - Unfortunately, there are only a few simple cases where these parameter estimates have <code>closed-form solutions</code>; i.e., we cannot generally write out the parameter estimates in terms of the observed data like we could for the single probability estimate <span class="math inline">\pi</span> in Section 1.1.2.</p>
<ul>
<li>Instead, we use iterative numerical procedures, as described in Appendix B.3.2, to successively find estimates of the regression parameters that increase the log-likelihood function</li>
</ul>
</section>
<section id="parameter-estimation-in-r" class="level2">
<h2 class="anchored" data-anchor-id="parameter-estimation-in-r">parameter estimation in R</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#get data</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>placekick <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="fu">here</span>(<span class="st">"data"</span>,<span class="st">"Placekick.csv"</span>),<span class="at">header =</span> T, <span class="at">sep =</span> <span class="st">","</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>placekick <span class="sc">%&gt;%</span> head <span class="sc">%&gt;%</span> <span class="fu">kable</span>(<span class="st">"html"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">"striped"</span>, <span class="st">"hover"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">week</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">distance</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">change</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">elap30</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">PAT</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">type</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">field</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">wind</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">good</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">21</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">24.7167</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">21</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">15.8500</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.4500</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">28</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">13.5500</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">21.8667</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">17.6833</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
</tr>
</tbody>
</table>


</div>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">#fit the model</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>mod.fit <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="at">formula =</span> good <span class="sc">~</span> distance , <span class="at">family =</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">binomial</span>(<span class="at">link =</span> logit), <span class="at">data =</span> placekick)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>latex_equation <span class="ot">&lt;-</span> <span class="fu">extract_eq</span>(mod.fit)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(latex_equation)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$$
\log\left[ \frac { P( \operatorname{good} = \operatorname{1} ) }{ 1 - P( \operatorname{good} = \operatorname{1} ) } \right] = \alpha + \beta_{1}(\operatorname{distance})
$$</code></pre>
</div>
</div>
</section>
</section>
<section id="odds" class="level1">
<h1>ODDS</h1>
<ul>
<li>see page 83, the odd of success at a particular value of <code>x</code></li>
</ul>
<p><span class="math display">\text{Odds}_x = \text{exp}(\beta_0 + \beta_1x)</span></p>
</section>
<section id="log-odds-to-probability" class="level1">
<h1>Log odds to probability</h1>
<ul>
<li><p>Your aunt offers a service in which she weights coins to make them unfair.</p></li>
<li><p>You give her a coin and tell her how much you want the <code>log-odds</code> to change. She returns the modified coin.</p></li>
<li><p>For each of the following orders, use your function to compute the resulting probability of heads:</p>
<ul>
<li>fair coin, increase log-odds by 1.</li>
<li>fair coin, increase log-odds by 2.</li>
<li>fair coin, increase log-odds by 10.</li>
<li>fair coin, decrease log-odds by 1.</li>
<li>fair coin, decrease log-odds by 2.</li>
<li>fair coin, decrease log-odds by 10.</li>
</ul></li>
<li><p>Write an R function that computes the <code>probability of heads</code>, given log-odds.</p></li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">log_odds</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">probability</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">10</td>
<td style="text-align: right;">1.000</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.881</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.731</td>
</tr>
<tr class="even">
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.500</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-1</td>
<td style="text-align: right;">0.269</td>
</tr>
<tr class="even">
<td style="text-align: right;">-2</td>
<td style="text-align: right;">0.119</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-10</td>
<td style="text-align: right;">0.000</td>
</tr>
</tbody>
</table>


</div>
</div>
<ul>
<li>In you own words, describe how changes in log-odds translate to changes in probability</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="wk2_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>You can see in this plot, As log-odds increase, the probability of success increases relative to the probability of failure, and it approaches one. As log-odds decrease probability of success decrease and converges to zero.</p></li>
<li><p>If you get log-odds values that are very very small like -10 the probability of success is almost zero, and if you get log-odds values that are very big like 10 or the probability of success is almost one.</p></li>
<li><p>The relationship between log-odd and probability is not linear, but of s-curve type, and log odds ratios ranging from -5 to +5 create probabilities that range from just above 0 to very close to 1.</p></li>
</ul>
</section>
<section id="case-study-south-african-heart-disease" class="level1">
<h1>Case Study: South African Heart Disease</h1>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<ul>
<li>Target: <code>Probability of getting coronary heart disease</code>, <code>chd</code></li>
<li>Feature:
<ul>
<li>High blood pressure, high LDL cholesterol, diabetes, smoking, secondhand smoke exposure, obesity, an unhealthy diet, and physical inactivity are among the leading risk factors for heart disease.</li>
</ul></li>
<li>Data Source: Source: Rousseauw, J., du Plessis, J., Benade, A., Jordaan, P., Kotze, J. and Ferreira, J. (1983). Coronary risk factor screening in three rural communities, South African Medical Journal 64: 430–436.</li>
</ul>
</section>
<section id="data-description" class="level2">
<h2 class="anchored" data-anchor-id="data-description">Data Description</h2>
<ul>
<li>sbp: systolic blood pressure</li>
<li>tobacco: cumulative tobacco use (kg)</li>
<li>ldl: low density lipoprotein cholesterol (‘bad’ cholestrol)</li>
<li>adiposity: Body adiposity index determines body fat percentage(calculated as (HC / (HM)1.5) - 18, where HC = Hip Circumference in Centimetres and HM = Height in meters)</li>
<li>famhist: family history of heart disease</li>
<li>typea: A personality type that could raise one’s chances of developing coronary heart disease</li>
<li>obesity: Body Mass Index (BMI) (<span class="math inline">kg/m^2</span>)</li>
<li>alcohol: current alcohol consumption</li>
<li>age: age at onset</li>
<li><code>chd</code>: coronary heart disease</li>
</ul>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="exploratory-analysis" class="level1">
<h1>Exploratory Analysis</h1>
<p>For this case study, we focus on blood pressure, smoking, cholesterol, and age.</p>
<ul>
<li><p>Load the data and answer the following questions:</p>
<ul>
<li>What are the number of variables and number of observations?</li>
<li>What is the type of each variable? Do we need to change it?</li>
<li>Are there any missing values (in each of the variables)?</li>
<li>Are there any abnormal values in each of the variables in the raw data?</li>
</ul></li>
</ul>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">tobacco</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">ldl</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">sbp</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">age</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">chd</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">obesity</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">12.00</td>
<td style="text-align: right;">5.73</td>
<td style="text-align: right;">160</td>
<td style="text-align: right;">52</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">25.30</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">4.41</td>
<td style="text-align: right;">144</td>
<td style="text-align: right;">63</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">28.87</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0.08</td>
<td style="text-align: right;">3.48</td>
<td style="text-align: right;">118</td>
<td style="text-align: right;">46</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">29.14</td>
</tr>
<tr class="even">
<td style="text-align: right;">7.50</td>
<td style="text-align: right;">6.41</td>
<td style="text-align: right;">170</td>
<td style="text-align: right;">58</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">31.99</td>
</tr>
<tr class="odd">
<td style="text-align: right;">13.60</td>
<td style="text-align: right;">3.50</td>
<td style="text-align: right;">134</td>
<td style="text-align: right;">49</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">25.99</td>
</tr>
<tr class="even">
<td style="text-align: right;">6.20</td>
<td style="text-align: right;">6.47</td>
<td style="text-align: right;">132</td>
<td style="text-align: right;">45</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">30.77</td>
</tr>
</tbody>
</table>


</div>
</div>
<section id="univariate-analysis" class="level2">
<h2 class="anchored" data-anchor-id="univariate-analysis">Univariate Analysis</h2>
<ul>
<li><p>The response (or dependent) variable of interest, Heart disease, is a binary variable taking the type factor.</p></li>
<li><p>Use a bar chart to explore the distribution of the response variable (chd). What do you learn?</p></li>
</ul>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Heart disease</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">N</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Proportion</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: right;">302</td>
<td style="text-align: right;">0.65</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">160</td>
<td style="text-align: right;">0.35</td>
</tr>
</tbody>
</table>


</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="wk2_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>For metric variables, a density plot or histogram allows us to determine the shape of the distribution and look for outliers.</p>
<ul>
<li>Use a density plot to explore the distribution of explanatory variables. What do you discover?</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="wk2_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="bivariate-analysis" class="level2">
<h2 class="anchored" data-anchor-id="bivariate-analysis">Bivariate Analysis</h2>
<ul>
<li><p>Prior to moving on to the fully specified model, it is advisable to first examine the simple associations between the response and each explanatory variable.</p></li>
<li><p><code>Box plots</code> are useful for exploring the association between a categorical variable and a variable measured on an interval scale.</p></li>
<li><p>Use a <code>boxplot</code> to examine how the explanatory variables are correlated with the response variable (chd)?</p>
<ul>
<li>The <code>coord_flip()</code> function is used to keep the dependent variable on the y-axis.</li>
</ul></li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="wk2_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div style="page-break-after: always;"></div>
<ul>
<li>Use the convenient summary_factorlist() function from the finalfit package to tabulate data.</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Dependent: chd</th>
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: left;" data-quarto-table-cell-role="th">0</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">1</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">ldl</td>
<td style="text-align: left;">Mean (SD)</td>
<td style="text-align: left;">4.3 (1.9)</td>
<td style="text-align: left;">5.5 (2.2)</td>
<td style="text-align: left;">&lt;0.001</td>
</tr>
<tr class="even">
<td style="text-align: left;">sbp</td>
<td style="text-align: left;">Mean (SD)</td>
<td style="text-align: left;">135.5 (18.0)</td>
<td style="text-align: left;">143.7 (23.7)</td>
<td style="text-align: left;">&lt;0.001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">tobacco</td>
<td style="text-align: left;">Mean (SD)</td>
<td style="text-align: left;">2.6 (3.6)</td>
<td style="text-align: left;">5.5 (5.6)</td>
<td style="text-align: left;">&lt;0.001</td>
</tr>
<tr class="even">
<td style="text-align: left;">age</td>
<td style="text-align: left;">Mean (SD)</td>
<td style="text-align: left;">38.9 (14.9)</td>
<td style="text-align: left;">50.3 (10.6)</td>
<td style="text-align: left;">&lt;0.001</td>
</tr>
</tbody>
</table>


</div>
</div>
<ul>
<li>According to the plots and the tables, What variable is most important for explaining heart disease? How is that variable correlated with heart disease?</li>
</ul>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="model-development" class="level1">
<h1>Model Development</h1>
<section id="linear-probability-model" class="level2">
<h2 class="anchored" data-anchor-id="linear-probability-model">Linear probability model</h2>
<ul>
<li><p>Is the linear probability model an appropriate choice to study the relationship between heart disease and risk factors?</p></li>
<li><p>Estimate the following linear probability model and interpret the model results.</p></li>
</ul>
<p><span class="math display"> chd = \beta_0 + \beta_1 ldl + \beta_2 sbp + + \beta_3 tobacco + \beta_4 age + u</span></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = chd ~ ldl + sbp + tobacco + age, data = df)

Residuals:
    Min      1Q  Median      3Q     Max 
-0.8439 -0.3405 -0.1250  0.4365  1.0172 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -0.3493578  0.1405912  -2.485 0.013315 *  
ldl          0.0362419  0.0102322   3.542 0.000438 ***
sbp          0.0009739  0.0010670   0.913 0.361839    
tobacco      0.0165577  0.0049101   3.372 0.000809 ***
age          0.0076831  0.0016886   4.550 6.89e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.4318 on 457 degrees of freedom
Multiple R-squared:  0.1853,    Adjusted R-squared:  0.1781 
F-statistic: 25.98 on 4 and 457 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ul>
<li>What are the advantages and disadvantages of the linear probability model?</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="wk2_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div style="page-break-after: always;"></div>
</section>
<section id="generalized-linear-model" class="level2">
<h2 class="anchored" data-anchor-id="generalized-linear-model">Generalized linear model</h2>
<ul>
<li>Estimate the following logistic regression model and interpret the model results.</li>
</ul>
<p><span class="math display"> logit(\pi_i) =\beta_0 + \beta_1 ldl + \beta_2 sbp + + \beta_3 tobacco + \beta_4 age +  u</span></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = chd ~ ldl + sbp + tobacco + age, family = binomial(link = logit), 
    data = df)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-1.9457  -0.8595  -0.4999   1.0238   2.3906  

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -4.535524   0.781360  -5.805 6.45e-09 ***
ldl          0.185131   0.054121   3.421 0.000625 ***
sbp          0.004307   0.005394   0.798 0.424623    
tobacco      0.075982   0.025616   2.966 0.003016 ** 
age          0.046264   0.009852   4.696 2.66e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 596.11  on 461  degrees of freedom
Residual deviance: 502.19  on 457  degrees of freedom
AIC: 512.19

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<section id="interpretation-of-model-results" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-of-model-results">Interpretation of model results</h3>
<ul>
<li>Do the <code>raw</code> coefficient estimates <code>directionally make sense</code>?</li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = chd ~ ldl + sbp + tobacco + age, family = binomial(link = logit), 
    data = df)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-1.9457  -0.8595  -0.4999   1.0238   2.3906  

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -4.535524   0.781360  -5.805 6.45e-09 ***
ldl          0.185131   0.054121   3.421 0.000625 ***
sbp          0.004307   0.005394   0.798 0.424623    
tobacco      0.075982   0.025616   2.966 0.003016 ** 
age          0.046264   0.009852   4.696 2.66e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 596.11  on 461  degrees of freedom
Residual deviance: 502.19  on 457  degrees of freedom
AIC: 512.19

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<ul>
<li><blockquote class="blockquote">
<p><strong>Again, all of the explanatory variables except blood pressure are statistically significant and positively correlated with the probability of heart disease, same as the linear probability model.</strong></p>
</blockquote></li>
<li>Recall that (page 83)</li>
</ul>
<p><span class="math display">
\text{OR} = \frac{\text{Odds}_{x_k+c}}{\text{Odds}_{x_k}}=exp(c \beta_k)
</span> - The odd of a success change by exp(c<span class="math inline">\beta_k</span>) <code>times</code> for every c-unit increase in x</p>
<ul>
<li>Compute and interpret the estimated odds ratio for a 10-unit increase in each explanatory variable.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Replace with your code</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">exp</span>(<span class="dv">10</span><span class="sc">*</span><span class="fu">coef</span>(mod.logit.h0)),<span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)         ldl         sbp     tobacco         age 
       0.00        6.37        1.04        2.14        1.59 </code></pre>
</div>
</div>
<blockquote class="blockquote">
<p><strong>The estimated odds of success or having a heart disease change by 6.37 times for every 10-unit increase in LDL or ‘bad’ cholesterol.</strong></p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Interestingly, the odds of having a heart disease is almost 1 for every 10-unit increase in blood pressure, which means an increase in blood pressure doesn’t change the odds of having heart disease, and it’s consistent with its insignificant coefficient.</strong></p>
</blockquote>
</section>
</section>
</section>
<section id="statistical-inference" class="level1">
<h1>Statistical Inference</h1>
<section id="hypothesis-test" class="level2">
<h2 class="anchored" data-anchor-id="hypothesis-test">Hypothesis Test</h2>
<ul>
<li><p>Using the likelihood ratio test (LRT) for hypothesis testing is a common practice in a logistic regression model.</p></li>
<li><p>Use LRT to test whether (<span class="math inline">obesity</span>) is associated with heart disease.</p>
<ul>
<li><p><span class="math inline">H_0: \beta_{obesity} = 0</span></p></li>
<li><p><span class="math inline">H_a: \beta_{obesity} \ne 0</span></p></li>
</ul></li>
</ul>
<p>Use both <em>Anova()</em> or <em>anova()</em> functions.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co">#mod.logit.ha &lt;- # uncomment and replace with your code</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>mod.logit.ha <span class="ot">&lt;-</span> <span class="fu">glm</span>(chd <span class="sc">~</span> ldl <span class="sc">+</span> sbp <span class="sc">+</span>tobacco <span class="sc">+</span> age <span class="sc">+</span> obesity, <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> logit), <span class="at">data =</span> df)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="co">#anova()</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod.logit.h0, mod.logit.ha, <span class="at">test =</span> <span class="st">"Chisq"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table

Model 1: chd ~ ldl + sbp + tobacco + age
Model 2: chd ~ ldl + sbp + tobacco + age + obesity
  Resid. Df Resid. Dev Df Deviance Pr(&gt;Chi)
1       457     502.19                     
2       456     501.07  1   1.1191   0.2901</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Anova()</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">Anova</span>(mod.logit.ha, <span class="at">test =</span> <span class="st">"LR"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table (Type II tests)

Response: chd
        LR Chisq Df Pr(&gt;Chisq)    
ldl      13.3932  1  0.0002525 ***
sbp       0.8640  1  0.3526279    
tobacco   9.4670  1  0.0020920 ** 
age      24.3447  1  8.055e-07 ***
obesity   1.1191  1  0.2901078    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
<section id="deviance" class="level2">
<h2 class="anchored" data-anchor-id="deviance">Deviance</h2>
<ul>
<li><p><code>deviance</code> refers to the amount that a particular model deviates from another model as measured by <span class="math inline">-2\text{log}(\Lambda)</span>.</p></li>
<li><p>What are the null deviance and residual deviance in the model summary?</p>
<ul>
<li>For <code>null</code> and <code>residual deviance</code>, the alternative model we use is the <code>saturated model</code>, which has a different coefficent for each data point, leading to perfect prediction, a likelihood of one, and a log likelihood of zero.</li>
</ul></li>
<li><p>The <code>null deviance</code> measures the performance of the worst model using only <code>an intercept</code>, providing a benchmark.</p></li>
</ul>
<p><span class="math display">
\text{Null Deviance}= -2 \text{log}(L(\hat{\beta_0}|y_1,..., y_n))
</span></p>
<ul>
<li>The <code>residual deviance</code> is the deviance of our fitted model.
<ul>
<li>It is always greater than zero unless it is the saturated model / explains the data perfectly.</li>
</ul></li>
</ul>
<p><span class="math display">
\text{Residual Deviance}= -2 \text{log}(L(\hat{\beta}|y_1,..., y_n))
</span></p>
<ul>
<li><p>Therefore, how much better (smaller) our residual deviance is compared to the null deviance and how close it is to zero is a measure of model fit.</p></li>
<li><p>Sometimes people will compute an <span class="math inline">R^2</span> for logistic regression using <span class="math inline">1-\frac{\text{Residual Deviance}}{\text{Null Deviance}}</span> since it is bounded between 0 (residual deviance = null deviance) and 1 (residual deviance = saturated model = 0).</p></li>
<li><p>Note that we can compute deviance of two separate models by substracting the null model residual deviance and the alternative model residual deviance from separate logistic regression fits. (Why is this?)</p></li>
<li><p>Using deviance, test whether (<span class="math inline">obesity</span>) is associated with heart disease.</p>
<ul>
<li><p><span class="math inline">H_0: \beta_{obesity} = 0</span></p></li>
<li><p><span class="math inline">H_a: \beta_{obesity} \ne 0</span></p></li>
</ul></li>
</ul>
<blockquote class="blockquote">
<p><strong>We get a p-value of 0.29, the same as what we got from both anova() and Anova() functions, and again we fail to reject the null hypothesis that obesity is not correlated with heart disease given this data set.</strong></p>
</blockquote>
</section>
<section id="confidence-interval" class="level2">
<h2 class="anchored" data-anchor-id="confidence-interval">Confidence Interval</h2>
<section id="confidence-interval-for-odds-ratio" class="level3">
<h3 class="anchored" data-anchor-id="confidence-interval-for-odds-ratio">Confidence Interval for odds ratio</h3>
<p><strong>Wald Confidence:</strong></p>
<p><span class="math display">
c*\hat{\beta_k} \pm c*Z_{1-\alpha/2} \sqrt{\widehat{Var}(\hat{\beta}_k)}
</span></p>
<p><span class="math display">
exp \left(c*\hat{\beta_k} \pm c*Z_{1-\alpha/2} \sqrt{\widehat{Var}(\hat{\beta}_k)} \right)
</span></p>
<ul>
<li>Calculate Wald CI for odds ratio of 10-unit increase in LDL cholesterol based on the above formula:</li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>             (Intercept)           ldl           sbp       tobacco
(Intercept)  0.610523787 -9.955527e-03 -3.315082e-03  1.122271e-03
ldl         -0.009955527  2.929029e-03 -1.336470e-05 -4.923675e-06
sbp         -0.003315082 -1.336470e-05  2.909849e-05 -1.506782e-06
tobacco      0.001122271 -4.923675e-06 -1.506782e-06  6.562050e-04
age         -0.001828353 -6.178475e-05 -1.503794e-05 -7.699037e-05
                      age
(Intercept) -1.828353e-03
ldl         -6.178475e-05
sbp         -1.503794e-05
tobacco     -7.699037e-05
age          9.706566e-05</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  2.20 18.39</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p><strong>With 95% confidence, the odds of having a heart disease change between 2.20 to 18.4 times for every 10-unit increase in LDL or ‘bad’ cholesterol.</strong></p>
</blockquote>
<ul>
<li>What is the main concern with Wald CI?</li>
</ul>
<blockquote class="blockquote">
<p><strong>Wald confidence interval has a true confidence level close to the 95% only when we have large samples. When the sample size is not large, profile LR confidence intervals generally perform better.</strong></p>
</blockquote>
<ul>
<li>Now calculate the <em>profile likelihood ratio (LR)</em> confidence interval using the confint function.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Replace with your code</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>beta_ci <span class="ot">&lt;-</span> <span class="fu">confint</span>(mod.logit.h0)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Waiting for profiling to be done...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>odds_ci <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="dv">10</span><span class="sc">*</span>beta_ci)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">cbind</span>(odds_ci ),<span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            2.5 % 97.5 %
(Intercept)  0.00   0.00
ldl          2.24  18.84
sbp          0.94   1.16
tobacco      1.31   3.59
age          1.31   1.93</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Since we have a large sample, 462 observations, the profile likelihood ratio (LR) confidence interval is pretty close to the Wald CI.</strong></p>
</blockquote>
</section>
<section id="confidence-interval-for-the-probability-of-success" class="level3">
<h3 class="anchored" data-anchor-id="confidence-interval-for-the-probability-of-success">Confidence Interval for the Probability of Success</h3>
<ul>
<li>Recall that the estimated probability of success is <span class="math display">
\hat{\pi} = \frac{exp \left( \hat{\beta}_0 + \hat{\beta}_1 x_1 + \dots + \hat{\beta}_K x_k \right)}{1+exp \left(\hat{\beta}_0 + \hat{\beta}_1 x_1 + \dots + \hat{\beta}_K x_k \right)}
</span></li>
</ul>
<p>While backing out the estimated probability of success is straightforward, obtaining its confidence interval is not, as it involves many parameters.</p>
<p><strong>Wald Confidence Interval</strong></p>
<p><span class="math display">
\hat{\beta}_0 + \hat{\beta}_1 x_1 + \dots + \hat{\beta}_K x_K \pm Z_{1-\alpha/2} \sqrt{\widehat{Var}(\hat{\beta}_0 + \hat{\beta}_1 x_1 + \dots + \hat{\beta}_K x_K)}
</span></p>
<p>where</p>
<p><span class="math display">
\widehat{Var}(\hat{\beta}_0 + \hat{\beta}_1 x_1 + \dots + \hat{\beta}_K x_K) = \sum_{i=0}^K x_i^2 \widehat{Var}(\hat{\beta_i}) + 2 \sum_{i=0}^{K-1} \sum_{j=i+1}^{K} x_i x_j \widehat{Cov}(\hat{\beta}_i,\hat{\beta}_j)
</span></p>
<p>So, the Wald Interval for <span class="math inline">\pi</span> is</p>
<p><span class="math display">
\frac{exp \left( \hat{\beta}_0 + \hat{\beta}_1 x_1 + \dots + \hat{\beta}_K x_k \pm \sqrt{\sum_{i=0}^K x_i^2 \widehat{Var}(\hat{\beta_i}) + 2 \sum_{i=0}^{K-1} \sum_{j=i+1}^{K} x_i x_j \widehat{Cov}(\hat{\beta}_i,\hat{\beta}_j)}  \right)}{1+exp \left(\hat{\beta}_0 + \hat{\beta}_1 x_1 + \dots + \hat{\beta}_K x_k \right)  \pm \sqrt{\sum_{i=0}^K x_i^2 \widehat{Var}(\hat{\beta_i}) + 2 \sum_{i=0}^{K-1} \sum_{j=i+1}^{K} x_i x_j \widehat{Cov}(\hat{\beta}_i,\hat{\beta}_j)}}
</span></p>
<ul>
<li>For an average value of all explanatory variables, compute the Confidence Interval for the Probability of Success given the formula above</li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  pi.hat  lower  upper
1 0.3089 0.2925 0.3259</code></pre>
</div>
</div>
</section>
<section id="final-visualization" class="level3">
<h3 class="anchored" data-anchor-id="final-visualization">Final Visualization</h3>
<ul>
<li><p>Using both the linear probability and logistic regression models, plot the estimated probability of heart disease for different values of cholesterol, holding other variables constant at their average level.</p></li>
<li><p>Discuss which one can better explain this relationship.</p></li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="wk2_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div style="page-break-after: always;"></div>
</section>
<section id="final-report" class="level3">
<h3 class="anchored" data-anchor-id="final-report">Final Report</h3>
<ul>
<li>Display both estimated linear and logistic models in a regression table. Is there any significant difference between their results?</li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Table 1: The estimated relationship between heart disease and risk factors
==================================================
                         Dependent variable:      
                    ------------------------------
                                 chd              
                           OLS          logistic  
                           (1)             (2)    
--------------------------------------------------
ldl                      0.036***       0.185***  
                         (0.010)         (0.054)  
                                                  
sbp                       0.001           0.004   
                         (0.001)         (0.005)  
                                                  
tobacco                  0.017***        0.076**  
                         (0.005)         (0.026)  
                                                  
age                      0.008***       0.046***  
                         (0.002)         (0.010)  
                                                  
Constant                 -0.349*        -4.536*** 
                         (0.141)         (0.781)  
                                                  
--------------------------------------------------
Observations               462             462    
R2                        0.185                   
Adjusted R2               0.178                   
Log Likelihood                          -251.093  
Akaike Inf. Crit.                        512.187  
Residual Std. Error  0.432 (df = 457)             
==================================================
Note:                *p&lt;0.05; **p&lt;0.01; ***p&lt;0.001</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p><strong>In both models, all the coefficients except blood pressure are statistically significant and positively associated with the probability of having heart disease. Also, LDL is the most correlated variable with the probability of heart disease in both models.</strong></p>
</blockquote>
</section>
</section>
</section>
<section id="terms" class="level1">
<h1>Terms</h1>
<div class="cell">
<div id="tbl-penguins-top10" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-penguins-top10-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: First 10 Penguins
</figcaption>
<div aria-describedby="tbl-penguins-top10-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table table-striped table-hover do-not-create-environment cell caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">wk</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Term</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Description</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">$$\text{equals to}$$</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">wk1</td>
<td style="text-align: left;">odd</td>
<td style="text-align: left;">For a Bernoulli random variable with parameter $p$, the odds are defined as the ratio of the probability of success to the probability of failure,</td>
<td style="text-align: left;">$$\text{Odd}=\frac{p}{1-p}$$</td>
</tr>
<tr class="even">
<td style="text-align: left;">wk1</td>
<td style="text-align: left;">logit</td>
<td style="text-align: left;">This is log of odd</td>
<td style="text-align: left;">$$\text{logit}(p)=\text{log}\frac{p}{1-p}$$</td>
</tr>
<tr class="odd">
<td style="text-align: left;">wk1</td>
<td style="text-align: left;">odd</td>
<td style="text-align: left;">from logit, you can get odd. This expression will be used a lot later.</td>
<td style="text-align: left;">$$\text{exp}(x) =\frac{p}{1-p}$$</td>
</tr>
<tr class="even">
<td style="text-align: left;">wk1</td>
<td style="text-align: left;">probability</td>
<td style="text-align: left;">this is probability of success in binary respose case</td>
<td style="text-align: left;">$$p = \frac{exp(x)}{1+exp(x)}$$</td>
</tr>
<tr class="odd">
<td style="text-align: left;">wk2</td>
<td style="text-align: left;">saturated model</td>
<td style="text-align: left;">This model is frequently referred as the `saturated model` because the number of parameters is equal to the number of observations, so that no additional parameters can be estimated. It refers to observed proportions of success. See p81</td>
<td style="text-align: left;">$$\text{logit}(\pi_i) = \gamma_i$$</td>
</tr>
<tr class="even">
<td style="text-align: left;">wk2</td>
<td style="text-align: left;">likelihood</td>
<td style="text-align: left;">Also known as likelihood function. It measures how well a statistical model explains observed data by calculating the probability of seeing that data under different parameter values of the model.</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">wk2</td>
<td style="text-align: left;">likelihood ratio test</td>
<td style="text-align: left;">Likelihood ratio test (LRT) is a statistic. P17. Note that this is $\Lambda$</td>
<td style="text-align: left;">$$\Lambda = \frac{\text{MLR under} H_0}{\text{MLR under} H_0 \text{ or } H_a}$$</td>
</tr>
<tr class="even">
<td style="text-align: left;">wk2</td>
<td style="text-align: left;">deviance</td>
<td style="text-align: left;">the amount that a particular model deviates from another model measured by the transformed LRT,$-2log(\Lambda)$, see p 81</td>
<td style="text-align: left;">$$-2\text{log}(\Lambda)$$</td>
</tr>
<tr class="odd">
<td style="text-align: left;">wk2</td>
<td style="text-align: left;">null deviance</td>
<td style="text-align: left;">The null deviance denotes how much the probabilities estimated from the model logit$(\pi_i)=\beta_0$ for all observation. Measured in transformed LRT, $-2log(\Lambda)$</td>
<td style="text-align: left;">The $\pi_i$ is estaimted to be the same value for this particular model. See p81</td>
</tr>
<tr class="even">
<td style="text-align: left;">wk2</td>
<td style="text-align: left;">residual deviance</td>
<td style="text-align: left;">measures how much probabilities estimated from a model of interest deviatesfrom the `observed proportions of success`. Residual deviance statistics are often calculated as an intermediate step for performing a LRT to compare two models. Measured in transformed LRT, $-2log(\Lambda)$</td>
<td style="text-align: left;">It is a measure of overall goodness of fit for a model. When you have two different models $H_0$ and $H_a$, you can estimate `the transformed LRT` of $H_0$ by comparing the logit($\pi^{(0)}$ with `saturated model` and also that of $H_a$. When you subtract the transformed LRT of $H_0$ from that of $H_a$, it measures the probability of success under the $H_0$ and $H_a$. p77 and 81</td>
</tr>
<tr class="odd">
<td style="text-align: left;">wk2</td>
<td style="text-align: left;">transformed likelihood ratio test statistic</td>
<td style="text-align: left;">transformed likelihood ratio test (LRT) statistic follows chi-square degress of freedom. Recommend using it. Better than the Wald Interval</td>
<td style="text-align: left;">$$ -2log(\Lambda) = -2log( \frac{L(\hat{{\beta}}^{(0)} | y_1,..., y_n)}{L(\hat{{\beta}}^{(a)} | y_1,..., y_n)}) = -2\sum y_i log( \frac{\hat{\pi}_i^{(0)}}{\hat{\pi}_i^{(a)}}) + (1 - y_i ) log( \frac{1- \hat{\pi}_i^{(0)}}{1- \hat{\pi}_i^{(a)}}) $$</td>
</tr>
<tr class="even">
<td style="text-align: left;">wk2</td>
<td style="text-align: left;">$\text{Odds}_x$</td>
<td style="text-align: left;">The odds of a success at a particular value of x. p83</td>
<td style="text-align: left;">$$\text{Odds}_x = exp(\beta_0 + \beta_1x) $$</td>
</tr>
<tr class="odd">
<td style="text-align: left;">wk2</td>
<td style="text-align: left;">$\text{Odds}_{x+c}$</td>
<td style="text-align: left;">The odds of a success when x is changed by c. p83</td>
<td style="text-align: left;">$$\text{Odds}_{x+c} = exp(\beta_0 + \beta_1(x+c)) $$</td>
</tr>
<tr class="even">
<td style="text-align: left;">wk2</td>
<td style="text-align: left;">odd ratio</td>
<td style="text-align: left;">OR is operator. See the bottom of page 82. It should be E[X]. The odds of a success change by exp($c\beta_1$ ) times for every c-unit increase in x.</td>
<td style="text-align: left;">$$\frac{\text{Odds}_{x+c}}{\text{Odds}_x}=\frac{exp(\beta_0 + \beta_1(x+c))}{exp(\beta_0 + \beta_1x)}=exp(c\beta_1)$$</td>
</tr>
<tr class="odd">
<td style="text-align: left;">wk2</td>
<td style="text-align: left;">$\hat{\text{OR}}$</td>
<td style="text-align: left;">the estimated odd ratio, and its confidence interval can be found by `confint()`</td>
<td style="text-align: left;">$$\hat{\text{OR}} =\text{exp}(c\hat{\beta})$$</td>
</tr>
<tr class="even">
<td style="text-align: left;">wk3</td>
<td style="text-align: left;">$\hat{\pi}$</td>
<td style="text-align: left;">probability of succuss in logistic regression. P86</td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>


</div>
</div>
</figure>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>